# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CryptoSwift_test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 5.2'
  pod 'CryptoSwift', '~> 0.9.0'

end
